/**
 * Runs the real pipeline (FTZ -> internal model -> GEDCOM) against the provided sample
 * file and writes samples/family.ged + samples/export-report.md from the ACTUAL results
 * (counts, mapping warnings, round-trip report), not hand-written/fabricated numbers.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseFtzFile } from "../src/parser/index.js";
import { exportGedcom } from "../src/gedcom/export.js";
import { verifyRoundTrip } from "../src/gedcom/verify.js";

// Run from the repository root (this script is not part of the compiled package layout).
const ROOT = process.cwd();
const SAMPLE_PATH = path.join(ROOT, "Family Tree FTZ", "FamilyTree.ftz");

async function main() {
  const bytes = await readFile(SAMPLE_PATH);
  const { tree, validation: parseValidation } = await parseFtzFile(bytes, "FamilyTree.ftz");

  const exportResult = exportGedcom(tree, { sourceFileName: "FamilyTree.ftz" });
  if (exportResult.rejected) {
    throw new Error(`Export was rejected: ${exportResult.rejectionReason}`);
  }
  const gedcom = exportResult.gedcom!;

  await writeFile(path.join(ROOT, "samples", "family.ged"), gedcom, "utf-8");

  const report = verifyRoundTrip(tree, gedcom);

  const personCount = Object.keys(tree.persons).length;
  const familyCount = Object.keys(tree.families).length;
  const totalNotes = Object.values(tree.persons).reduce((sum, p) => sum + p.notes.length, 0);
  const gedcomNoteLines = (gedcom.match(/^1 NOTE /gm) ?? []).length;

  const unmappedWarnings = exportResult.issues.filter((i) => i.code === "UNMAPPED_FIELD_POPULATED");
  const dateWarnings = exportResult.issues.filter((i) => i.code === "UNFORMATTABLE_DATE");
  const parseErrors = parseValidation.issues.filter((i) => i.severity === "error");
  const parseWarnings = parseValidation.issues.filter((i) => i.severity === "warning");

  const md = `# Export Report — FamilyTree.ftz → family.ged

Generated by \`scripts/generate-samples.ts\` against the real sample file. Every number below comes from actually running the parser + exporter + round-trip verifier, not from documentation estimates.

## Summary

| Metric | Source tree | Generated GEDCOM | Match |
|---|---|---|---|
| People | ${personCount} | ${report.gedcomIndiCount} | ${report.personCountMatches ? "✓" : "✗ MISMATCH"} |
| Families | ${familyCount} | ${report.gedcomFamCount} | ${report.familyCountMatches ? "✓" : "✗ MISMATCH"} |
| Notes (NOTE lines) | ${totalNotes} | ${gedcomNoteLines} | ${totalNotes === gedcomNoteLines ? "✓" : "✗ MISMATCH"} |
| Cousin-marriage / shared-ancestor families | ${report.cousinMarriageCountSource} | ${report.cousinMarriageCountGedcom} | ${report.cousinMarriagesMatch ? "✓" : "✗ MISMATCH"} |

## Round-trip verification detail

- Relationship mismatches (FAMC/FAMS/HUSB/WIFE/CHIL): **${report.relationshipMismatches.length}**
- Note-count mismatches: **${report.noteCountMismatches.length}**
- Duplicate individuals detected: **${report.duplicateIndividuals.length}**
- Overall verification: **${report.passed ? "PASSED" : "FAILED"}**

## Fields mapped

See \`docs/gedcom-mapping.md\` for the full table. In summary: Person ID (REFN), name (NAME, heuristically split into GIVN/SURN), nickname (NICK), gender (SEX), birth year/month/day (BIRT/DATE), death year/month/day (DEAT/DATE), parent family (FAMC), spouse families (FAMS), notes (NOTE), family husband/wife (HUSB/WIFE), children with birth order (CHIL, in order), family ID (REFN).

## Fields that could not be mapped

Layout X/Y coordinates (Person and Family) — no GEDCOM concept exists for canvas position; intentionally omitted (documented in \`docs/gedcom-exporter.md\`), not lost from the internal model.

Beyond that: **zero** fields with actual data were left unmapped. The exporter scans every raw column that has no GEDCOM mapping (Person columns 2,5,6,9,10,11,12,15,16,27,28; Family columns 2,4,6,9,10,11,12 — 1-indexed) and would emit an \`UNMAPPED_FIELD_POPULATED\` warning if any were non-empty. Result on this file: **${unmappedWarnings.length} such warnings.**

## Warnings from this export

- Unmapped-but-populated fields: ${unmappedWarnings.length}
- Unformattable dates (month/day known without a year): ${dateWarnings.length}
- Parse-time errors carried into export: ${parseErrors.length}
- Parse-time warnings on the source tree: ${parseWarnings.length}

${
  exportResult.issues.length === 0
    ? "No warnings were raised during export."
    : exportResult.issues.map((i) => `- **[${i.severity}/${i.code}]** ${i.message}`).join("\n")
}

## Conclusion

${
  report.passed && unmappedWarnings.length === 0
    ? "The generated `family.ged` is a complete, verified, lossless (for every field with a known GEDCOM mapping) representation of the source FTZ file's genealogical data."
    : "See the mismatches/warnings above before treating this export as complete."
}
`;

  await writeFile(path.join(ROOT, "samples", "export-report.md"), md, "utf-8");

  console.log(
    JSON.stringify(
      {
        personCount,
        familyCount,
        totalNotes,
        gedcomNoteLines,
        roundTripPassed: report.passed,
        unmappedWarnings: unmappedWarnings.length,
      },
      null,
      2
    )
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
