export function AboutPage() {
  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100">
          About this project
        </h1>
      </div>

      <section>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">What is FTZ?</h2>
        <p className="mt-2 text-slate-600 dark:text-slate-400">
          <span className="font-mono">.ftz</span> is the file format used by the Quick Family Tree
          mobile app to export a family tree. It's a ZIP archive containing a tab-separated data
          file (<span className="font-mono">node.ftt</span>) with every person and family
          relationship in the tree. The format is undocumented by its original vendor — this
          project's format specification was reverse-engineered directly from real export files.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">
          Why GEDCOM matters
        </h2>
        <p className="mt-2 text-slate-600 dark:text-slate-400">
          GEDCOM is the open, vendor-neutral standard for exchanging genealogical data. Once your
          family tree is in GEDCOM format, it's no longer locked into one app — you can move it
          between genealogy programs, back it up in a durable open format, or hand it down without
          depending on any single company staying in business.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">
          Supported software
        </h2>
        <p className="mt-2 text-slate-600 dark:text-slate-400">
          Files generated by this tool target the GEDCOM 5.5.1 standard and have been tested with a
          real automated import into{" "}
          <a
            href="https://gramps-project.org"
            className="text-blue-700 underline dark:text-blue-400"
            rel="noopener noreferrer"
          >
            Gramps
          </a>
          , an open-source genealogy program, with zero structural errors. They're also designed to
          be compatible with RootsMagic, Legacy Family Tree, and FamilySearch, though those specific
          imports have not been automated-tested in this project's development environment.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Project goals</h2>
        <p className="mt-2 text-slate-600 dark:text-slate-400">
          Preserve family history data and free it from a single proprietary app. The parser is
          built to never duplicate a person, never silently discard information, and to surface
          every uncertainty rather than guess quietly.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">
          Open-source mission
        </h2>
        <p className="mt-2 text-slate-600 dark:text-slate-400">
          This project is free and open source. Anyone can read the code, verify how their data is
          handled, and contribute improvements — especially around the parts of the FTZ format that
          remain uncertain (see Limitations below).
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Limitations</h2>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-slate-600 dark:text-slate-400">
          <li>
            The FTZ format was reverse-engineered from a single real export file. Most fields are
            mapped with high confidence, but a handful of always-empty columns in that sample have
            unknown meaning — if your file populates one of them, you'll see a warning rather than
            silently losing that data.
          </li>
          <li>Photos and media attachments are not yet imported or exported.</li>
          <li>
            Name splitting into "given name" and "surname" for GEDCOM uses a simple heuristic and
            can misfire on unusual name formats.
          </li>
          <li>Editing your family tree in the browser is not yet supported — see the roadmap.</li>
        </ul>
      </section>
    </div>
  );
}
